### ISSUE TITLE
Cannot get cy-run.sh to work when executing on CircleCi

### ISSUE THREAD

**Issue by ChaseBig** [bahmutov/demo-docker-cypress-included#4]
I'm really struggling with getting `cypress/included` working with circleCi. I can run the `cy-run.sh` bash script on my local machine (mac osx) and it works/begins running my cypress tests but it doesn't work on circleCi. 

My codebase is a monorepo of many packages but only three web-app environments called `web.app-browser`, `admin-app-browser`, and `partner-app-browser`. I initially set up cypress to spin up localhost instances for each web-app individually and then ran all the tests from a single `./cypress` directory at the root but have been running into xvfb display port errors. So I decided to split the tests into individual packages and added cypress to each of the three app packages so tests could be executed from the package level so cypress would spin up a test run for each package and only run tests related to each package individually. I still ended up running into xvfb errors since I'm running all three localhost instances AND all three cypress run's on a single machine. 

So, that brings me here, I am now trying to implement the `cypress/included` docker image so that each app package run is running on a separate docker image. I'm attempting to make this work with circleCi since that's our CD/CI service, but I'm failing to get circleCi to correctly run cypress.

I keep getting errors relating to bein unable to find certain files, whether it be the cypress.json file or spec.js files. 

Here's the error output that causes the circleCi build to fail 
```
...
745536d95138: Extracting  30.92kB/30.92kB
$<3>$<3>
745536d95138: Extracting  30.92kB/30.92kB
$<3>$<3>
745536d95138: Pull complete 
Digest: sha256:34f67539d2c255ed24aa38b4edf11639d13579181915da9ad9e1e0b8e62ab564
Status: Downloaded newer image for cypress/included:3.7.0
^@^@Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Could not find a Cypress configuration file, exiting.

We looked but did not find a cypress.json file in this folder: /e2e
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1```

Here's my circleCi config.yml:
```
workflows:
  version: 2
  main:
    jobs:
      - test:
          context: blah-global 
        #   updated the `context:` line to a fake context for privacy sake

version: 2
jobs:
  test:
    docker:
      - image: ${AWS_ECR_PATH}/nodejs:10-web-ci
        aws_auth:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      - image: cypress/base:8
    parallelism: 3

    steps:
      - checkout
      # Clear yarn cache before run
      - run:
          name: clear cache
          command: yarn cache clean
      - run:
          name: Install Dependencies
          command: yarn install
      # Lint only changed files
      - run:
          name: Lint changed files
          command: yarn lint:changed-packages
      - run:
          name: Spin up localhost for changed packages
          command: yarn run:package-circle-localhost
          when: on_success
          background: true
          halt_build_on_fail: true
      - run:
          name: Confirm changed package localhost test servers are running
          command: yarn run:ping-changed-localhosts
          when: on_success
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run docker run bash script
          command: |
            bash cy-run.sh
          no_output_timeout: 1200
      - run:
          name: clear cypress cache
          command: |
            rm -rf /tmp/.X*
            yarn cypress:clear-cache
          when: on_success
      - run:
          name: Test changed packages
          command: yarn test:changed-packages --no-cache -w 1
          when: on_success
      - run:
          name: List changed packages
          command: yarn what-changed
```

**Comment by bahmutov** [comment]
Can you check what you are doing, since I have added a CircleCI build to this repo without any problems?

File: https://github.com/bahmutov/demo-docker-cypress-included/blob/master/circle.yml
Runs: https://app.circleci.com/pipelines/github/bahmutov/demo-docker-cypress-included?branch=master
